import React, { useEffect, useState } from 'react';
import { CalendarDays, LogOut, Search } from 'lucide-react';
import type { User } from '../types';
import { cancelAppointment, getAvailability, getLocations, getMyAppointments, getSpecialties, requestReschedule, reserveAppointment, SchedulingApiError, type Appointment, type AvailabilityOption, type Location, type Specialty } from './schedulingApi';

const nextDay = () => { const value = new Date(); value.setDate(value.getDate() + 1); return value.toISOString().slice(0, 10); };
const statuses: Record<Appointment['status'], string> = { APPROVED: 'Aprobada', REQUESTED: 'En revisión', REJECTED: 'Rechazada', CANCELLED: 'Cancelada', COMPLETED: 'Atendida', NO_SHOW: 'No asistió' };
const errorText = (error: unknown) => error instanceof SchedulingApiError ? error.message : 'No fue posible completar la operación.';
const input = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm focus:border-blue-500 focus:outline-none';

export function UserBookingScreen({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [specialties, setSpecialties] = useState<Specialty[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [specialtyId, setSpecialtyId] = useState(''); const [locationId, setLocationId] = useState(''); const [date, setDate] = useState(nextDay); const [options, setOptions] = useState<AvailabilityOption[]>([]); const [selected, setSelected] = useState<AvailabilityOption | null>(null); const [rescheduling, setRescheduling] = useState<Appointment | null>(null); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  const refresh = async () => { try { setAppointments(await getMyAppointments()); } catch (e) { setError(errorText(e)); } };
  useEffect(() => { Promise.all([getSpecialties(), getLocations(), getMyAppointments()]).then(([s, l, a]) => { setSpecialties(s); setLocations(l.filter((x) => x.active)); setAppointments(a); }).catch((e) => setError(errorText(e))); }, []);
  const search = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setSelected(null); try { setOptions(await getAvailability(Number(locationId), Number(specialtyId), date, rescheduling?.professionalId)); } catch (e) { setError(errorText(e)); } };
  const startReschedule = (appointment: Appointment) => { setRescheduling(appointment); setSpecialtyId(String(appointment.specialtyId)); setLocationId(String(appointment.locationId)); setDate(nextDay()); setOptions([]); setNotice(`Elige una nueva franja para ${appointment.specialtyName}. Al confirmarla, tu cita se actualizará de inmediato.`); };
  const confirm = async () => { if (!selected) return; setError(''); try { if (rescheduling) { await requestReschedule(rescheduling.id, selected.locationId, selected.startAt); setNotice('Cita reprogramada y confirmada correctamente.'); setRescheduling(null); } else { const result = await reserveAppointment({ professionalId: selected.professionalId, locationId: selected.locationId, specialtyId: selected.specialtyId, startAt: selected.startAt }); setNotice(result.status === 'APPROVED' ? 'Reserva confirmada y aprobada.' : 'Solicitud enviada para revisión administrativa.'); } setSelected(null); await refresh(); } catch (e) { setError(errorText(e)); } };
  const cancel = async (id: number) => { try { await cancelAppointment(id); setNotice('Cita cancelada. El horario fue liberado.'); await refresh(); } catch (e) { setError(errorText(e)); } };
  return <main className="w-full max-w-6xl space-y-6"><header className="flex items-center justify-between rounded-3xl bg-slate-900 p-6 text-white shadow-lg"><div className="flex items-center gap-3"><span className="rounded-2xl bg-blue-500 p-3"><CalendarDays /></span><div><h1 className="font-bold">Mis citas</h1><p className="text-sm text-slate-300">{user.name} · agenda y seguimiento</p></div></div><button onClick={onLogout} aria-label="Cerrar sesión" className="rounded-xl p-2 hover:bg-white/10"><LogOut /></button></header>
    {(notice || error) && <p role={error ? 'alert' : 'status'} className={`rounded-2xl border p-4 text-sm ${error ? 'border-red-200 bg-red-50 text-red-700' : 'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{error || notice}</p>}
    {rescheduling && <p className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Reprogramación en curso. <button type="button" className="font-semibold underline" onClick={() => setRescheduling(null)}>Cancelar proceso</button></p>}
    <section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="font-bold">{rescheduling ? 'Selecciona un nuevo horario' : 'Agenda una cita'}</h2><p className="mb-4 text-sm text-slate-500">Los horarios mostrados provienen de la disponibilidad real.</p><form onSubmit={search} className="grid gap-3 md:grid-cols-4"><select className={input} value={specialtyId} disabled={Boolean(rescheduling)} required onChange={(e) => setSpecialtyId(e.target.value)}><option value="">Especialidad</option>{specialties.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select className={input} value={locationId} required onChange={(e) => setLocationId(e.target.value)}><option value="">Sede</option>{locations.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={input} type="date" min={nextDay()} value={date} onChange={(e) => setDate(e.target.value)} /><button className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white"><Search className="mr-1 inline h-4 w-4" />Buscar</button></form><div className="mt-5 grid gap-3 md:grid-cols-3">{options.map((x) => <button type="button" key={`${x.professionalId}-${x.startAt}`} onClick={() => setSelected(x)} className={`rounded-2xl border p-4 text-left ${selected?.startAt === x.startAt ? 'border-blue-600 bg-blue-50' : 'border-slate-200'}`}><b>{x.professionalName}</b><p className="text-xs text-slate-500">{x.specialtyName} · {x.locationName}</p><p className="mt-2 text-sm">{x.startAt.slice(11, 16)} – {x.endAt.slice(11, 16)}</p></button>)}</div>{selected && <div className="mt-4 rounded-2xl bg-blue-50 p-4"><b>{rescheduling ? 'Confirma la reprogramación inmediata' : 'Confirma la reserva'}</b><p className="text-sm">{selected.startAt.replace('T', ' ').slice(0, 16)} · {selected.professionalName}</p><button type="button" onClick={confirm} className="mt-3 rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">{rescheduling ? 'Confirmar reprogramación' : 'Confirmar reserva'}</button></div>}</section>
    <section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="font-bold">Mis citas registradas</h2><button onClick={() => void refresh()} className="text-sm font-semibold text-blue-700">Actualizar</button></div><div className="mt-4 space-y-3">{appointments.length === 0 ? <p className="text-sm text-slate-500">Aún no tienes citas registradas.</p> : appointments.map((x) => <article key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-100 p-4"><div><p className="font-semibold">{x.specialtyName} <span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{statuses[x.status]}</span></p><p className="text-sm text-slate-600">{x.startAt.replace('T', ' ').slice(0, 16)} · {x.locationName}</p><p className="text-xs text-slate-500">Profesional: {x.professionalName}</p></div><div className="flex gap-2">{x.status === 'APPROVED' && <button onClick={() => startReschedule(x)} className="rounded-xl border border-blue-200 px-3 py-2 text-xs font-semibold text-blue-700">Reprogramar</button>}{['APPROVED', 'REQUESTED'].includes(x.status) && <button onClick={() => void cancel(x.id)} className="rounded-xl bg-red-600 px-3 py-2 text-xs font-semibold text-white">Cancelar</button>}</div></article>)}</div></section>
  </main>;
}
