import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Clock3, LogOut, Search, Stethoscope } from 'lucide-react';
import type { User } from '../types';
import { cancelAppointment, getAppointmentHistory, getAvailability, getLocations, getMyAppointments, getSpecialties, reserveAppointment, SchedulingApiError, type Appointment, type AppointmentHistory, type AvailabilityOption, type Location, type Specialty } from './schedulingApi';

const field = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-800 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20';
const tomorrow = () => { const value = new Date(); value.setDate(value.getDate() + 1); return value.toISOString().slice(0, 10); };
const message = (error: unknown) => error instanceof SchedulingApiError && error.status === 409 ? 'Ese horario acaba de cambiar. Busca nuevamente una opción disponible.' : error instanceof SchedulingApiError ? error.message : 'No fue posible completar la operación.';

export function UserBookingScreen({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [specialties, setSpecialties] = useState<Specialty[]>([]); const [locations, setLocations] = useState<Location[]>([]);
  const [specialtyId, setSpecialtyId] = useState(''); const [locationId, setLocationId] = useState(''); const [date, setDate] = useState(tomorrow);
  const [options, setOptions] = useState<AvailabilityOption[]>([]); const [selected, setSelected] = useState<AvailabilityOption | null>(null); const [reason, setReason] = useState('');
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [history, setHistory] = useState<Record<number, AppointmentHistory[]>>({}); const [appointmentsLoading, setAppointmentsLoading] = useState(true);
  const [loading, setLoading] = useState(true); const [searching, setSearching] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  useEffect(() => { Promise.all([getSpecialties(), getLocations()]).then(([s, l]) => { setSpecialties(s); setLocations(l.filter((item) => item.active)); }).catch((e) => setError(message(e))).finally(() => setLoading(false)); }, []);
  const reloadAppointments = async () => { setAppointmentsLoading(true); try { setAppointments(await getMyAppointments()); } catch (e) { setError(message(e)); } finally { setAppointmentsLoading(false); } };
  useEffect(() => { void reloadAppointments(); }, []);
  const selectedSpecialty = useMemo(() => specialties.find((item) => item.id === Number(specialtyId)), [specialties, specialtyId]);
  const search = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setSuccess(''); setSelected(null); setSearching(true); try { setOptions(await getAvailability(Number(locationId), Number(specialtyId), date)); } catch (e) { setError(message(e)); } finally { setSearching(false); } };
  const reserve = async () => { if (!selected) return; setError(''); try { const appointment = await reserveAppointment({ professionalId: selected.professionalId, locationId: selected.locationId, specialtyId: selected.specialtyId, startAt: selected.startAt, reason: reason || undefined }); setSuccess(appointment.status === 'APPROVED' ? 'Tu cita general fue aprobada automáticamente.' : 'Tu solicitud especializada fue enviada y conserva este horario.'); setOptions((current) => current.filter((item) => item.startAt !== selected.startAt || item.professionalId !== selected.professionalId)); setSelected(null); await reloadAppointments(); } catch (e) { setError(message(e)); } };
  const cancel = async (id: number) => { setError(''); try { await cancelAppointment(id); setSuccess('La cita fue cancelada y el horario quedó liberado.'); await reloadAppointments(); } catch (e) { setError(message(e)); } };
  const audit = async (id: number) => { try { const entries = await getAppointmentHistory(id); setHistory((current) => ({ ...current, [id]: entries })); } catch (e) { setError(message(e)); } };
  return <main className="w-full max-w-5xl space-y-6" id="user-booking-screen">
    <header className="rounded-2xl border border-slate-100 bg-white px-6 py-4 shadow-sm flex items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-600 p-2.5 text-white"><CalendarDays className="w-5 h-5" /></div><div><h1 className="font-bold text-slate-900">Buscar una cita</h1><p className="text-xs text-slate-500">{user.name} · disponibilidad real</p></div></div><button aria-label="Cerrar sesión" onClick={onLogout} className="rounded-xl p-2 text-slate-500 hover:bg-red-50 hover:text-red-600"><LogOut className="w-5 h-5" /></button></header>
    {(error || success) && <p role={error ? 'alert' : 'status'} className={`rounded-xl border p-3 text-sm ${error ? 'border-red-200 bg-red-50 text-red-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error || success}</p>}
    <form onSubmit={search} className="grid grid-cols-1 gap-4 rounded-3xl border border-slate-100 bg-white p-6 shadow-sm md:grid-cols-4"><select className={field} required value={specialtyId} disabled={loading} onChange={(e) => setSpecialtyId(e.target.value)}><option value="">Especialidad</option>{specialties.map((s) => <option value={s.id} key={s.id}>{s.name} · {s.appointmentDurationMinutes} min</option>)}</select><select className={field} required value={locationId} disabled={loading} onChange={(e) => setLocationId(e.target.value)}><option value="">Sede</option>{locations.map((l) => <option value={l.id} key={l.id}>{l.code}</option>)}</select><input className={field} type="date" min={tomorrow()} value={date} onChange={(e) => setDate(e.target.value)} required /><button disabled={!specialtyId || !locationId || searching} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:bg-slate-300 flex items-center justify-center gap-2"><Search className="w-4 h-4" />{searching ? 'Buscando…' : 'Buscar'}</button></form>
    <section className="rounded-3xl border border-slate-100 bg-white p-6 shadow-sm"><div className="mb-4 flex items-center gap-2"><Stethoscope className="w-5 h-5 text-blue-600" /><h2 className="font-bold">Horarios disponibles</h2></div>{!searching && options.length === 0 ? <p className="text-sm text-slate-500">Selecciona los filtros y busca. Solo se mostrarán franjas completas y reservables.</p> : <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">{options.map((option) => <button type="button" key={`${option.professionalId}-${option.startAt}`} onClick={() => setSelected(option)} className={`rounded-2xl border p-4 text-left hover:border-blue-400 ${selected === option ? 'border-blue-600 bg-blue-50' : 'border-slate-200'}`}><p className="font-semibold text-slate-800">Profesional #{option.professionalId}</p><p className="mt-1 flex items-center gap-1 text-sm text-slate-500"><Clock3 className="w-4 h-4" />{option.startAt.slice(11, 16)}–{option.endAt.slice(11, 16)}</p><p className="mt-2 text-xs text-blue-700">{option.general ? 'Cita general: aprobación automática' : 'Cita especializada: requiere decisión ADMIN'}</p></button>)}</div>}</section>
    {selected && <section className="rounded-3xl border border-blue-100 bg-white p-6 shadow-sm"><h2 className="font-bold">Confirmar {selectedSpecialty?.name}</h2><p className="mt-1 text-sm text-slate-500">{selected.startAt.slice(0, 10)} · {selected.startAt.slice(11, 16)} · Profesional #{selected.professionalId}</p><textarea className={`${field} mt-4`} maxLength={500} placeholder="Motivo opcional" value={reason} onChange={(e) => setReason(e.target.value)} /><button type="button" onClick={reserve} className="mt-4 rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white">Confirmar reserva</button></section>}
    <section className="rounded-3xl border border-slate-100 bg-white p-6 shadow-sm"><h2 className="mb-4 font-bold">Mis citas</h2>{appointmentsLoading ? <p className="text-sm text-slate-400">Cargando tus citas…</p> : appointments.length === 0 ? <p className="text-sm text-slate-500">Aún no tienes citas registradas.</p> : <div className="space-y-3">{appointments.map((appointment) => <article key={appointment.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{appointment.specialtyName} · {appointment.status}</p><p className="text-sm text-slate-500">{appointment.startAt.replace('T', ' ').slice(0, 16)} · {appointment.locationName} · {appointment.professionalName}</p>{appointment.reason && appointment.status === 'REJECTED' && <p className="mt-1 text-xs text-red-600">Motivo: {appointment.reason}</p>}</div><div className="flex gap-2"><button type="button" onClick={() => void audit(appointment.id)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold">Auditoría</button>{['APPROVED', 'REQUESTED'].includes(appointment.status) && <button type="button" onClick={() => void cancel(appointment.id)} className="rounded-lg bg-red-600 px-3 py-2 text-xs font-semibold text-white">Cancelar</button>}</div></div>{history[appointment.id] && <ol className="mt-3 border-t border-slate-100 pt-3 text-xs text-slate-500">{history[appointment.id].map((entry, index) => <li key={`${entry.changedAt}-${index}`}>{entry.changedAt.replace('T', ' ').slice(0, 16)} · {entry.status} · {entry.source}</li>)}</ol>}</article>)}</div>}</section>
  </main>;
}
